### ISSUE TITLE
failed SanityTest on parancoe-plugin-italy - trunk

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xingbaichao/parancoe#3]
```
Test set: org.parancoe.plugins.italy.SanityTest
Environment: JDK 1.6.0_06/Ubuntu 8.04/Dell XPS1530

log trace:

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.552 sec
<<< FAILURE!
testPlugin(org.parancoe.plugins.italy.SanityTest)  Time elapsed: 3.397 sec
 <<< ERROR!
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'handlerMapping' defined in class path resource
[org/parancoe/web/parancoeBase.xml]: Initialization of bean failed; nested
exception is org.springframework.beans.factory.BeanCreationException: Error
creating bean with name 'dwrController': Invocation of init method failed;
nested exception is java.lang.IllegalStateException:
WebApplicationObjectSupport instance
[org.directwebremoting.spring.DwrController@16a4a67] does not run in a
WebApplicationContext but in:
org.springframework.context.support.GenericApplicationContext@d08633:
display name
[org.springframework.context.support.GenericApplicationContext@d08633];
startup date [Sun Jun 01 20:14:04 IST 2008]; root of context hierarchy
    at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doC
reateBean(AbstractAutowireCapableBeanFactory.java:470)
    at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory$1.r
un(AbstractAutowireCapableBeanFactory.java:404)
    at java.security.AccessController.doPrivileged(Native Method)
    at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.cre
ateBean(AbstractAutowireCapableBeanFactory.java:375)
    at
org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(Abstra
ctBeanFactory.java:263)
    at
org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingle
ton(DefaultSingletonBeanRegistry.java:170)
    at
org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(Abstract
BeanFactory.java:260)
    at
org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBe
anFactory.java:184)
    at
org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBe
anFactory.java:163)
    at
org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstanti
ateSingletons(DefaultListableBeanFactory.java:430)
    at
org.springframework.context.support.AbstractApplicationContext.finishBeanFactory
Initialization(AbstractApplicationContext.java:729)
    at
org.springframework.context.support.AbstractApplicationContext.refresh(AbstractA
pplicationContext.java:381)
    at
org.springframework.test.AbstractSingleSpringContextTests.createApplicationConte
xt(AbstractSingleSpringContextTests.java:243)
    at
org.springframework.test.AbstractSingleSpringContextTests.loadContextLocations(A
bstractSingleSpringContextTests.java:212)
    at
org.springframework.test.AbstractSingleSpringContextTests.loadContext(AbstractSi
ngleSpringContextTests.java:187)
    at
org.springframework.test.AbstractSpringContextTests.getContext(AbstractSpringCon
textTests.java:140)
    at
org.springframework.test.AbstractSingleSpringContextTests.setUp(AbstractSingleSp
ringContextTests.java:100)
    at junit.framework.TestCase.runBare(TestCase.java:125)

```

Original issue reported on code.google.com by `enricogi...@gmail.com` on 1 Jun 2008 at 7:20

**Comment by GoogleCodeExporter** [comment]
```
The problem has not been appeared any more so it seems was not an bug
```

Original comment by `enricogi...@gmail.com` on 2 Dec 2009 at 2:03
- Changed state: **Invalid**
